version: '3.3'

services:

 server:
   build:
    context: .
    dockerfile: ServerDockerfile
   ports:
    - "4000:4000"
   volumes:
    - .:/app
   tty: true
   networks:
    - "net"

 mongo:
  image: mongo
  restart: always
  ports:
    - "27017:27017"
  networks:
   - "net"

networks:
  net:
    driver: bridge
