version: "3.3"

services:
 auth-server:
   build:
    context: .
    dockerfile: docker/PythonDockerfile
   ports:
    - "4000:4000"
   networks:
    - "net"

 mongo:
  image: mongo
  ports:
    - "27017:27017"
  networks:
   - "net"
  volumes:
   - ./Docker/MongoDB:/data/db

networks:
  net:
    driver: bridge
