version: '3.3'

services:
 
 server:
   build:
    context: .
    dockerfile: ServerDockerfile
   ports:
    - "443:4000"
   volumes:
    - .:/app
   tty: true

 mongo:
  image: mongo
  restart: always
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: example
 
